/* exported FeedSelector */
const FeedSelector = "[role='main'] div > h3 + div:not([class])";

/* exported WatchFeedSelector */
const WatchFeedSelector =
  "[role='main'] div#watch_feed > div > div > div > div > div:not([class])";

/* exported MESSAGE_CODE */
const MESSAGE_CODE = {
  UPDATE_BADGE_TEXT: "UPDATE_BADGE_TEXT",
};

/* exported sponsorWordsFilter */
const sponsorWordsFilter = [
  // Legit valid words
  "Sponsored", // English
  "مُموَّل", // Arabic
  "Giisponsoran", // Danish
  "Sponsorisé", // French
  "Publicidad", // Spanish
  "La maalgeliyey", // Af-Soomaaali
  "Geborg", // Afrikaans
  "Reklam", // Azərbaycan dili
  "Реклама", // Russian
  "Bersponsor", // Bahasa Indonesia
  "Ditaja", // Bahasa Melayu
  // Generated by ChatGpt
  "स्पॉन्सर्ड",
  "赞助内容",
  "広告",
  "دارای پشتیبانی مالی",
  "Kanthi Sponsor",
  "Paeroniet",
  "Patrocinat",
  "Spunsurizatu",
  "Noddwyd",
  "Babestua",
  "May Sponsor",
  "Yoɓanaama",
  "Sponsorizât",
  "Stuðlað",
  "Urraithe",
  "Gesponsert", // German
  "Sponsorizzato", // Italian
  "Patrocinado", // Portuguese
  "Спонсируемый", // Russian
  "スポンサード", // Japanese
  "赞助", // Chinese (Simplified)
  "प्रायोजित", // Hindi
  "스폰서", // Korean
  "Gesponsord", // Dutch
  "Sponsor", // Swedish
  "Sponsorerede", // Danish
  "Sponset", // Norwegian
  "Sponsoroidut", // Finnish
  "Sponsorowane", // Polish
  "Sponsorlu", // Turkish
  "Χορηγούμενο", // Greek
  "Sponzorováno", // Czech
  "Támogatott", // Hungarian
  "Sponsorizat", // Romanian
  "Disponsori", // Indonesian
  "Được tài trợ", // Vietnamese
  "ผู้สนับสนุน", // Thai
  "Ditaja", // Malay
  "ממומן", // Hebrew
  "Спонсоровано", // Ukrainian
  "Спонсорирано", // Bulgarian
  "Patrocinat", // Catalan
  "Sponsoreret", // Danish
  "Sponsorált", // Hungarian
  "Χορηγούμενη", // Greek
  "Sponsorowane", // Polish
  "Подпомогнат", // Macedonian
  "Sponsorisht", // Albanian
  "Patrocinat", // Romanian
  "Sponsrad", // Swedish
  "Sponzorirano", // Slovenian
  "Patrocinat", // Occitan
  "Sponsoroitu", // Finnish
  "Sponsrad", // Swedish
  "Sponzorirano", // Bosnian
  "Sponsorerad", // Swedish
  "Sponsort", // Luxembourgish
  "Esponsorizado", // Galician
  "Patrocinado", // Asturian
  "פּאַטראָספירט", // Yiddish
  "ಸ್ಪಾನ್ಸರ್", // Kannada
  "முகாமையான", // Tamil
  "স্পন্সরযোগ্য", // Bengali
  "స్పాన్సర్", // Telugu
  "സ്പോൺസർഡ്", // Malayalam
  "ස්පෝන්සර්", // Sinhala
  "سپانسر", // Pashto
  "پنچانگی", // Urdu
  "سپانسر", // Kashmiri
  "سپانسر", // Sindhi
  "পৰমৰ্শক", // Assamese
  "স্পনসর", // Bengali
  "ସ୍ପନସରଡ୍", // Odia
  "স্পনসরকৃত", // Assamese
  "স্পনসরকৃত", // Bengali
  "સ્પોન્સર", // Gujarati
  "સ્પોન્સરડ", // Gujarati
  "संवर्धित", // Marathi
  "स्पोन्सर्ड", // Nepali
  "সৰ্বদলীয়", // Assamese
  "সহায়িত", // Bengali
  "ପ୍ରଯୋଜିତ", // Odia
  "பொறுப்பு", // Tamil
  "ప్రొత్సాహించబడిన", // Telugu
  "ಬೆಂಬಲಿತ", // Kannada
  "പ്രായോജിച്ചത്", // Malayalam
  "සහභාගී", // Sinhala
  "خاندهار", // Pashto
  "نیازمند", // Urdu
  "سامارا", // Kashmiri
  "سپونسرډ", // Pashto
  "ସଂରକ୍ଷିତ", // Odia
  "স্বাস্থ্যকর", // Bengali
  "સંરક્ષિત", // Gujarati
  "संगठित", // Marathi
  "प्रायोजित", // Nepali
  "પોતાનીને", // Gujarati
  "தனித்துவ", // Tamil
  "అమలు", // Telugu
  "ನಿರಪೇಕ್ಷ", // Kannada
  "സ്വന്തമായ", // Malayalam
  "වෙනුවෙන්", // Sinhala
  "تحت", // Pashto
  "زیر", // Urdu
  "وستوئید", // Kashmiri
  "دریځیږی", // Pashto
  "ରୂପରେ", // Odia
  "উজ্জ্বল", // Bengali
  "ઉજ્જવળ", // Gujarati
  "निरंकुश", // Marathi
  "प्रायोजित", // Nepali
  "પુરાવાં", // Gujarati
  "அணுகல்", // Tamil
  "గొత్తు", // Telugu
  "ಹಕ್ಕುದಾರರು", // Kannada
  "അനുസരിച്ച്", // Malayalam
  "වරක්", // Sinhala
  "په", // Pashto
  "مطابق", // Urdu
  "جيبنه", // Kashmiri
  "پامیګر", // Pashto
  "ମଧ୍ୟ", // Odia
  "উপর", // Bengali
  "પર", // Gujarati
  "सामग्री", // Marathi
  "प्रायोजित", // Nepali
  "પર", // Gujarati
  "மேல்", // Tamil
  "పైన", // Telugu
  "ಮೇಲೆ", // Kannada
  "പതിപ്പിക്കപ്പെട്ട", // Malayalam
  "සඳහා", // Sinhala
  "دی", // Pashto
  "کی", // Urdu
  "حسب", // Arabic
  "آژانس", // Persian
  "ترویجی", // Persian
  "تبلیغی", // Persian
  "حمایتی", // Persian
  "حمایتی", // Persian
  "تبلیغاتی", // Persian
  "تبلیغاتی", // Persian
  "تبلیغاتی", // Persian
  "ترویجی", // Persian
  "دعاوی", // Persian
  "تبلیغی", // Persian
];
